### ISSUE TITLE
ZCoin client shows the wrong transfer values 

### ISSUE THREAD

**Issue by hakonamatata** [firoorg/firo-client#137]
Zcoin client is not showing the correct transfer values. This was transfers to myself to fund a zcoin master node. 

<img width="1054" alt="client bug" src="https://user-images.githubusercontent.com/4003969/85513604-73a78a80-b5fb-11ea-97e4-9d8d278173f2.PNG">

![image](https://user-images.githubusercontent.com/4003969/85513534-65f20500-b5fb-11ea-8fc8-45aa791cf84c.png)

The ZCoin core client shows the correct values

**Comment by sproxet** [comment]
Hi, I'm not quite sure I understand. The transaction amounts shown in QT look like there is one transaction of approximately 10 XZC, and three transactions of 479 satoshi. In order to fund a Znode, a single transaction of 1000 XZC (100,000,000,000 satoshi) is required. To confirm, the issue is that you made 3 transactions with a value of 479 satoshi, and these are not properly displayed in the Electron wallet?

**Comment by hakonamatata** [comment]
> 
> 
> Hi, I'm not quite sure I understand. The transaction amounts shown in QT look like there is one transaction of approximately 10 XZC, and three transactions of 479 satoshi. In order to fund a Znode, a single transaction of 1000 XZC (100,000,000,000 satoshi) is required. To confirm, the issue is that you made 3 transactions with a value of 479 satoshi, and these are not properly displayed in the Electron wallet?

Sorry, I was not clear. It is not a transaction to fund a ZCoin, it is a transaction to register a ZCoin masternode on the blockchain using https://github.com/zcoinofficial/znode-tool-evo 

I followed this guide https://github.com/zcoinofficial/zcoin/wiki/Migrating-your-Legacy-Znodes-to-the-new-Deterministic-Znodes-system

**Comment by sproxet** [comment]
@camakira This looks to be related to the deterministic znode stuff.
